# Create a small crystal with GBs

# paths (relative to gpumd/ root)
nep_model: potentials/Si_GAP_nep.txt
gpumd_exec: /home/djr2473/exec/gpumd

# RNEMD parameters
rnemd:
  # control rnemd setup
  nbins: 50                # must be even (symmetric PBC paths)
  # control simulation length, total steps = n_cycles * steps_per_cycle
  timestep_fs: 1
  n_cycles: 1000                # number of production cycles (velocity swaps after each)
  steps_per_cycle: 100           # controls the frequency of velocity swaps
  # control replications
  n_runs: 3                # independent rNEMD simulations per structure (for uncertainty)
  # control simulation parameters
  ensemble: "nve"
  temperature_k: 675
  # control debugging plots (can be slow)
  debug_structure: False
  debug_diagnostics: True

# GB specifications
grain_boundaries:
- axis: [1, 0, 0]
  sigma: 5
  plane: [0, 1, 2]
- axis: [1, 0, 0]
  sigma: 13
  plane: [0, -3, 2]
